# Generated by Django 3.2 on 2022-09-03 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_data_migration'),
    ]

    operations = [
    ]
